# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmuyBtnRZ6O9jbwf_9KVCxslC4xlXT1G
"""

# Task 2 (EDA) & Task 3 (Data Visualization)
# Topic: Simple IPL Cricket Data Analysis


import pandas as pd
import matplotlib.pyplot as plt

# 1. Create Simple IPL Dataset
data = {
    'Team': ['Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders', 'RCB', 'Delhi Capitals'],
    'Total_Wins': [5, 5, 2, 0, 0]
}
df = pd.DataFrame(data)

# --- TASK 2: EXPLORATORY DATA ANALYSIS (EDA) ---
print("--- Dataset Overview ---")
print(df.head())           # Display data
print("\nDataset Info:")
print(df.info())           # Check structure

# --- TASK 3: DATA VISUALIZATION ---
plt.figure(figsize=(7, 4))
plt.bar(df['Team'], df['Total_Wins'], color='skyblue')
plt.title('IPL Trophy Wins by Team')
plt.xlabel('Teams')
plt.ylabel('Trophies Won')
plt.xticks(rotation=30)
plt.show()

print("\nAnalysis Completed Successfully!")